# Site settings
title:       Stripe Connector
author:      WhiteSky Labs
description: "MuleSoft Connector for Stripe"
baseurl:     "/stripe-connector"
url:         "http://whitesky-labs.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
# markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     1
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
