[[stripe-anypoint-connector]]
Stripe Anypoint Connector
-------------------------

By http://www.whiteskylabs.com[WhiteSky Labs]

Payments Infrastructure for the Internet.

[[community-connector]]
Community Connector
~~~~~~~~~~~~~~~~~~~

This connector developed by WhiteSky Labs is now part of Mulesoft's collection of Community Connectors. As a Community Connector, MuleSoft’s developer community can now contribute in the development and maintenance of the Stripe Connector.

[[how-to-contribute]]
How to Contribute
~~~~~~~~~~~~~~~~~

Below are some guidelines on how to submit your changes (patches/fixes/features):
* Clone the repository (https://github.com/WhiteSky-Labs/stripe-connector).
* Create a branch from master.
* Make your changes and commit them.
* Push up your changes.
* Make a pull request.

[[installation-and-usage]]
Installation and Usage
~~~~~~~~~~~~~~~~~~~~~~

For information about usage and installation you can review the
documentation at http://whitesky-labs.github.io/stripe-connector/about/.

API Documentation is available at
http://whitesky-labs.github.io/stripe-connector/apidocs

[[compatibility]]
Compatibility
~~~~~~~~~~~~~

The Stripe Connector is certified to be compatible with: * Mule ESB
v3.6.x  to v3.9.x * CloudHub Runtime v3.6.x to v3.9.x

[[reporting-issues]]
Reporting Issues
~~~~~~~~~~~~~~~~

Issues will be used to keep track of bugs, enhancements, or other requests. To submit an issue, go to the Issue tab on the Stripe Connector repository and create a new issue.
